### PR TITLE
Updated openshift_setup to release client.

### PR DESCRIPTION
**Pull request by cfchase**
Updated openshift_setup to use most current releases of clients instead of unstable mirror download.

### CODE REVIEW

**Comment by shawn-hurley** [comment]
ACK - this worked for me thanks @cfchase

**Comment by jwmatthews** [comment]
I'm running a test on mac, will update in a bit

**Comment by jwmatthews** [comment]
Confirming 3.6 and 3.7 both came up on mac with this PR.

**Comment by jwmatthews** [comment]
ACK

**Pull request merged**
