### PR TITLE
PR to remove etcd setup from CATASB

### PR DESCRIPTION
**Pull request by shawn-hurley**
https://github.com/openshift/ansible-service-broker/pull/838

### CODE REVIEW

**Comment by shawn-hurley** [comment]
[(21) Remove etcd from Broker and move to using CRDs](https://trello.com/c/K6zUdfLZ/668-21-remove-etcd-from-broker-and-move-to-using-crds)

**Comment by jmrodri** [comment]
Will I need this for working on a previous version of the broker? Maybe the answer is we go back to a previous commit and use the one that has etcd support in it. It would be great to have the ability to keep it but I fear if we keep it around it will get stale and won't work anyway. Having a not working setup is worse than no setup at all.

**Comment by shawn-hurley** [comment]
@jmrodri I think your mostly right. I could do something where if `crd_type` is `etcd` that we do the ssl stuff. 

I personally would not be opposed from branching and "releasing" catasb for the last release? 

That way master points and works with master templates and older version of catasb works with older version of template and image?

**Comment by jmontleon** [comment]
@jmrodri @rthallisey @shawn-hurley can we revert this? It breaks --rcm which uses the downstream images, which don't have the crd dao.

I imagine the blocks could be updated rather than removing them completely. Something along the lines of:

when: 
  - etcd_ca_cert is not defined and etcd_client_cert is not defined and etcd_client_key is not defined
  - dao == "etcd" or (rcm is defined and rcm)

Might take a little more manipulating wtih the -p options, but should be doable. Let me know if you need help.

**Comment by rthallisey** [comment]
let's do a follow up pr

**Pull request merged**
