### PR TITLE
Remove deprecation warnings for include

### PR DESCRIPTION
**Pull request by djzager**

### CODE REVIEW

**Comment by rthallisey** [comment]
@djzager does this require a minimal ansible version? In the README I see 2.3.0 min.

**Comment by jmrodri** [comment]
@djzager anything holding this up? can it be merged?

**Comment by djzager** [comment]
@jmrodri looking at Ryan's comment for the first time I realize now that I need to update the docs to specify the ansible version min is 2.4.0.

**Comment by djzager** [comment]
@jmrodri now it's ready

**Pull request merged**
