### PR TITLE
Merge dev into master

### PR DESCRIPTION
**Pull request by cfchase**
Merged dev into master: https://github.com/fusor/catasb/pull/87/commits/1d07987b0d0dc56707fefa355aa827493a1799d9
Fixed failure if error on checking oc version: https://github.com/fusor/catasb/pull/87/commits/d0ecfdbecb82ed71db47f3d8db24314151ed5191
Added note for Summit 2017: https://github.com/fusor/catasb/pull/87/commits/cce92064a343368cfe9bb8ee40777473a5f3af79

### CODE REVIEW

**Comment by cfchase** [comment]
[(2) Update catasb branches so master becomes our latest development work and the summit2017 demo is branched to 'summit2017'](https://trello.com/c/h21CkfNL/319-2-update-catasb-branches-so-master-becomes-our-latest-development-work-and-the-summit2017-demo-is-branched-to-summit2017)

**Comment by cfchase** [comment]
For merging this one, let's create a merge commit.

**Comment by jmrodri** [comment]
Merge commit enabled by the repo

**Comment by johnkim76** [comment]
successfully tested in Linux environment

**Comment by jwmatthews** [comment]
ACK

**Pull request merged**
