### PR TITLE
Merge master into dev + fixes.

### PR DESCRIPTION
**Pull request by cfchase**
Merged in master to dev branch and reverted commit that uses summit code.

### CODE REVIEW

**Comment by cfchase** [comment]
I've tested linux and ec2.  If someone could look/test out mac, that would be very helpful.

**Comment by jwmatthews** [comment]
Ran on mac and saw an issue:

TASK [ansible_service_broker_setup : set_fact] ************************************************************************************************************************
ok: [localhost]

TASK [ansible_service_broker_setup : uri] *****************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'not response.json or not response.json.SpecCount or response.json.SpecCount == 0' failed. The error was: error while evaluating conditional (not response.json or not response.json.SpecCount or response.json.SpecCount == 0): 'dict object' has no attribute 'SpecCount'"}
	to retry, use: --limit @/git/fusor/catasb/ansible/reset_mac_environment.retry

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=74   changed=44   unreachable=0    failed=1   


real	4m30.898s
user	0m33.905s
sys	0m12.913s


Yet when I try the route it looks good:

$ curl -X POST http://asb-1338-ansible-service-broker.192.168.37.1.nip.io/v2/bootstrap
{
  "spec_count": 8,
  "image_count": 10
}

I will debug more on my end, but might not have the time till Friday.

**Comment by jwmatthews** [comment]
Retested today and had success.

Ran through the postgres + python webapp demo on macOS with this PR.

**Comment by jwmatthews** [comment]
ACK

**Pull request merged**
