### PR TITLE
Integrate templates into the playbooks

### PR DESCRIPTION
**Pull request by rthallisey**
Instead of using asbcli to create the broker, use templates
and render them with jinja2.

### CODE REVIEW

**Comment by rthallisey** [comment]
I don't run catasb for development. Can someone help me verify?

**Comment by jwmatthews** [comment]
@rthallisey I'll take a look at this tomorrow.

**Comment by jwmatthews** [comment]
Pushed some changes to address issues I saw with testing.

**Comment by jwmatthews** [comment]
ACK

**Pull request merged**
