### PR TITLE
Add the public-hostname flag back

### PR DESCRIPTION
**Pull request by rthallisey**

### CODE REVIEW

**Comment by jmontleon** [comment]
@rthallisey, my understanding is this option is being removed. @shawn-hurley can you confirm I didn't misunderstand?

**Comment by rthallisey** [comment]
@jmontleon do you know if it's being replaced? Have a related pr issue link?

**Comment by jmontleon** [comment]
@rthallisey I don't. That's why i asked @shawn-hurley for clarification. I still see it available as an option in the current openshift 3.10 binary. He mentioned it on an email thread but I don't see anything searching openshift-origin open PR's or anything else.

**Comment by jmontleon** [comment]
ACK. Sounds like it may have been a rejecfed proposal.

**Pull request merged**
