### PR TITLE
Integrate templates into the playbooks

### PR DESCRIPTION
**Pull request by rthallisey**
Instead of using asbcli to create the broker, use templates and render them with jinja2.

I tested this by hooking asbcli up to it, not the service catalog.  I'll do the full e2e test with the catalog tomorrow.

The ansibleplaybookbundle broker image was not working, but the ansibleapp broker images was. I'm assuming that image was under development when I pulled it.  I'll do testing with the ansibleplaybookbundle broker image again tomorrow.

### CODE REVIEW

**Comment by jwmatthews** [comment]
Current thoughts are to hold off on merging this till post demo.

Then to rework the ASB build/deploy inline with this PR.

**Comment by jmrodri** [comment]
Reapply this PR against the dev branch please.

**Comment by cfchase** [comment]
@rthallisey @jmrodri @jwmatthews is this still desired for the dev branch?

**Comment by rthallisey** [comment]
I haven't had a change to move to the dev branch yet, but it will re use the templates as a way to deploy the broker.

**Comment by rthallisey** [comment]
https://github.com/fusor/catasb/pull/57

**Pull request closed without merging**
