### PR TITLE
Gate testing

### PR DESCRIPTION
**Pull request by rthallisey**
The gate requires a different setup process.  We only want to setup the openshift cluster with the proper networking and the service-catalog. In addition, the gate runs in Ubuntu which requires a a few changes.

### CODE REVIEW

**Comment by jwmatthews** [comment]
What do you think about reusing the local/linux workflow instead of introducing a new gate set of files?

I imagine we'd need to:
 
 - Update config/linux_env_vars to detect if it needs to add "| cut -f 2 -d ':')" to PUBLIC_IP   
   We can probably find a clean way to do this

 - Add a parameter/environment variable that when specified will skip 
   https://github.com/fusor/catasb/blob/master/ansible/setup_local_environment.yml#L18

Those were the major changes I saw between the local linux flow and the gate flow.

**Comment by jwmatthews** [comment]
What if we switched to using "ip addr"?
PUBLIC_IP="$(ip addr show docker0 | grep -Po 'inet \K[\d.]+')"

Does that behavior differ as well between ubuntu/redhat?

It seems like we can simplify most of this config to reuse the existing local/linux if can address setting PUBLIC_IP in a way that works for both.

**Comment by rthallisey** [comment]
There's no difference in behaviour it's just the ip gathering.

**Comment by rthallisey** [comment]
https://github.com/openshift/ansible-service-broker/pull/291 passed on previous commit. Re-triggering it after changing how we gather the public ip.

**Comment by jwmatthews** [comment]
What are your thoughts with consolidating setup_gate_environment.yml with setup_local_environment.yml?
I think the only difference is we do not want to deploy ASB when running in 'gate' mode.


We could find a way to set a variable:  skip_asb_deployment=true when running the gate setup.
Maybe something like:

cd catasb/local/linux
SKIP_ASB=true ./run_setup_local.sh

Then we add 'skip_asb_deploy: false" to 
https://github.com/fusor/catasb/blob/master/ansible/group_vars/all.yml

Allow 'skip_asb_deploy' to be overridden in gather_config if SKIP_ASB is defined.
SKIP_ASB="${SKIP_ASB:-false}"
export SKIP_ASB
extra_args="skip_asb_deploy:${SKIP_ASB}"

Then conditionally include ansible_serivce_broker_setup role
https://github.com/fusor/catasb/blob/master/ansible/setup_local_environment.yml#L18

From:
    - ansible_service_broker_setup
To:
    - { role: ansible_service_broker, when: not skip_asb_deploy }

**Comment by jwmatthews** [comment]
ACK, I'm good with this approach.

**Pull request merged**
